package com.smartspend;
import jakarta.persistence.*;import jakarta.validation.constraints.*;import lombok.*;import java.math.BigDecimal;import java.time.*;import java.util.*;
@Entity @Table(name="users") @Getter @Setter @NoArgsConstructor class User {@Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id;@NotBlank String name;@Column(unique=true,nullable=false) String email;@Column(nullable=false) String password;@Enumerated(EnumType.STRING) Role role=Role.USER;boolean active=true;LocalDateTime createdAt=LocalDateTime.now();}
enum Role{USER,ADMIN} enum PaymentMethod{CASH,CARD,UPI,NET_BANKING,WALLET}
@Entity @Getter @Setter @NoArgsConstructor class Category{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(unique=true,nullable=false)String name;String color="#38bdf8";Category(String n){name=n;}}
@Entity @Getter @Setter @NoArgsConstructor class Expense{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Positive BigDecimal amount;@NotBlank String description;LocalDate date;@ManyToOne(optional=false)Category category;@Enumerated(EnumType.STRING)PaymentMethod paymentMethod;@ManyToOne(optional=false)User user;LocalDateTime createdAt=LocalDateTime.now();Expense(BigDecimal a,String d,LocalDate dt,Category c,PaymentMethod p,User u){amount=a;description=d;date=dt;category=c;paymentMethod=p;user=u;}}
@Entity @Getter @Setter @NoArgsConstructor class Income{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Positive BigDecimal amount;@NotBlank String source;String description;LocalDate date;@ManyToOne(optional=false)User user;Income(BigDecimal a,String s,String d,LocalDate dt,User u){amount=a;source=s;description=d;date=dt;user=u;}}
@Entity @Getter @Setter @NoArgsConstructor class Budget{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Positive BigDecimal amount;@Column(name="budget_month")@Min(1)@Max(12)int month;@Column(name="budget_year")@Min(2000)int year;@ManyToOne Category category;@ManyToOne(optional=false)User user;}
@Entity @Getter @Setter @NoArgsConstructor class Notification{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne User user;String message,type;boolean readFlag=false;LocalDateTime createdAt=LocalDateTime.now();}
@Entity @Getter @Setter @NoArgsConstructor class SavingsGoal{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@NotBlank String title;@Positive BigDecimal targetAmount;@PositiveOrZero BigDecimal currentAmount;LocalDate deadline;@OneToOne(optional=false)User user;SavingsGoal(String t,BigDecimal target,BigDecimal current,LocalDate d,User u){title=t;targetAmount=target;currentAmount=current;deadline=d;user=u;}}
@Entity @Getter @Setter @NoArgsConstructor class AuditLog{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;String action,description,ipAddress;LocalDateTime timestamp=LocalDateTime.now();@ManyToOne User user;}
record AuthRequest(@NotBlank @Email String email,@NotBlank String password){} record RegisterRequest(@NotBlank String name,@NotBlank @Email String email,@NotBlank @Size(min=6)String password){} record ExpenseRequest(@Positive BigDecimal amount,@NotBlank String description,@NotNull LocalDate date,@NotNull Long categoryId,@NotNull PaymentMethod paymentMethod){} record IncomeRequest(@Positive BigDecimal amount,@NotBlank String source,String description,@NotNull LocalDate date){} record BudgetRequest(@Positive BigDecimal amount,@Min(1)@Max(12)int month,@Min(2000)int year,Long categoryId){} record SavingsGoalRequest(@NotBlank String title,@Positive BigDecimal targetAmount,@NotNull @PositiveOrZero BigDecimal currentAmount,LocalDate deadline){}
interface UserRepo extends org.springframework.data.jpa.repository.JpaRepository<User,Long>{Optional<User> findByEmail(String email);long countByRole(Role role);long countByActive(boolean active);}
interface CategoryRepo extends org.springframework.data.jpa.repository.JpaRepository<Category,Long>{Optional<Category> findByNameIgnoreCase(String name);}
interface ExpenseRepo extends org.springframework.data.jpa.repository.JpaRepository<Expense,Long>,org.springframework.data.jpa.repository.JpaSpecificationExecutor<Expense>{List<Expense> findByUserIdOrderByDateDesc(Long id);Optional<Expense> findByIdAndUserId(Long id,Long uid);org.springframework.data.domain.Page<Expense> findByUserIdOrderByDateDesc(Long id,org.springframework.data.domain.Pageable pageable);List<Expense> findByUserIdAndDateBetween(Long id,LocalDate a,LocalDate b);}
interface IncomeRepo extends org.springframework.data.jpa.repository.JpaRepository<Income,Long>,org.springframework.data.jpa.repository.JpaSpecificationExecutor<Income>{List<Income> findByUserIdOrderByDateDesc(Long id);Optional<Income> findByIdAndUserId(Long id,Long uid);org.springframework.data.domain.Page<Income> findByUserIdOrderByDateDesc(Long id,org.springframework.data.domain.Pageable pageable);List<Income> findByUserIdAndDateBetween(Long id,LocalDate a,LocalDate b);}
interface BudgetRepo extends org.springframework.data.jpa.repository.JpaRepository<Budget,Long>{List<Budget> findByUserId(Long id);Optional<Budget> findByIdAndUserId(Long id,Long uid);}
interface SavingsGoalRepo extends org.springframework.data.jpa.repository.JpaRepository<SavingsGoal,Long>{Optional<SavingsGoal> findByUserId(Long id);Optional<SavingsGoal> findByIdAndUserId(Long id,Long uid);}
interface NotificationRepo extends org.springframework.data.jpa.repository.JpaRepository<Notification,Long>{List<Notification> findByUserIdOrderByCreatedAtDesc(Long id);Optional<Notification> findByIdAndUserId(Long id,Long uid);}
interface AuditRepo extends org.springframework.data.jpa.repository.JpaRepository<AuditLog,Long>{List<AuditLog> findAllByOrderByTimestampDesc();org.springframework.data.domain.Page<AuditLog> findPageByOrderByTimestampDesc(org.springframework.data.domain.Pageable pageable);}
