const API = window.SMARTSPEND_API_BASE || 'http://localhost:8080/api';
const pageName = location.pathname.split('/').pop().replace('.html', '') || 'index';
const $ = (selector) => document.querySelector(selector);
const token = () => localStorage.getItem('smartspend_token');
const currentUser = () => JSON.parse(localStorage.getItem('smartspend_user') || '{}');

async function api(path, options = {}) {
  const headers = { ...(options.headers || {}) };
  if (options.body && !headers['Content-Type']) headers['Content-Type'] = 'application/json';
  if (token()) headers.Authorization = `Bearer ${token()}`;
  const response = await fetch(API + path, { ...options, headers });
  if (response.status === 401) {
    localStorage.removeItem('smartspend_token');
    localStorage.removeItem('smartspend_user');
    if (!['login', 'register', 'index'].includes(pageName)) location.href = 'login.html';
    throw new Error('Your session has expired. Please log in again.');
  }
  if (response.status === 403) throw new Error('You do not have permission to perform this action.');
  if (!response.ok) {
    let message = 'Unable to complete the request.';
    try { message = (await response.json()).message || message; } catch (_) { /* non-JSON response */ }
    throw new Error(message);
  }
  return response.status === 204 ? null : response.json();
}

function showMessage(text, kind = 'info') {
  const target = $('#message');
  if (target) { target.textContent = text; target.className = `message ${kind}`; }
}
function showLoading(text = 'Loading...') { const target = $('#app'); if (target) target.innerHTML = `<div class="loading">${text}</div>`; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function applyTheme(theme) {
  const next = theme === 'dark' ? 'dark' : 'light';
  document.documentElement.dataset.theme = next;
  localStorage.setItem('smartspend_theme', next);
  const button = $('#themeToggle');
  if (button) { button.textContent = next === 'dark' ? '☀️ Light' : '🌙 Dark'; button.setAttribute('aria-label', next === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'); }
}
function bindThemeToggle() { if (document.documentElement.dataset.themeBound === '1') return; document.documentElement.dataset.themeBound = '1'; document.addEventListener('click', (event) => { const button = event.target.closest('#themeToggle'); if (!button) return; event.preventDefault(); applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'); }); }
function initTheme() { applyTheme(localStorage.getItem('smartspend_theme') || 'light'); bindThemeToggle(); }
function categoryIcon(name = '') {
  const icons = { Food:'🍔', Transport:'🚗', Shopping:'🛍️', Bills:'🧾', Education:'🎓', Entertainment:'🎬', Health:'❤️', Travel:'✈️', Other:'📦', EMI:'💳', Borrow:'🤝', Rent:'🏠', Fuels:'⛽', Electronics:'💻', 'Mobile & Internet':'📱', Groceries:'🛒', 'Medical & Medicines':'💊', 'Courses & Certifications':'📚', 'Software & Subscriptions':'💿', 'Banking & Finance':'🏦', 'Gifts & Donations':'🎁', Pets:'🐾', Clothing:'👕', 'Personal Care':'💇', Fitness:'🏋️', 'Movies & Streaming':'📺', 'Dining Out':'🍽️', 'Rent & Housing':'🏠', Utilities:'💡', Insurance:'🛡️', Gifts:'🎁', 'Home Maintenance':'🧰', 'Vehicle Maintenance':'🔧', 'Parking & Tolls':'🅿️', 'Public Transport':'🚌', 'Books & Stationery':'📚', Games:'🎮', 'Coffee & Snacks':'☕', Household:'🧹', Vacation:'🏖️', 'Pet Care':'🐾', Investment:'📈', Taxes:'🧾' };
  return icons[name] || '📁';
}
function safeColor(value, fallback = '#64748b') { return /^#[0-9a-fA-F]{6}$/.test(String(value || '')) ? value : fallback; }
function categoryColor(category) { const colors = { Food: '#f97316', Transport: '#2563eb', Shopping: '#7c3aed', Bills: '#eab308', Education: '#4f46e5', Entertainment: '#db2777', Health: '#dc2626', Travel: '#0891b2', Other: '#64748b', EMI:'#0f766e', Borrow:'#8b5cf6', Rent:'#059669', Fuels:'#f59e0b', Electronics:'#0ea5e9', 'Mobile & Internet':'#06b6d4', Groceries:'#16a34a', 'Medical & Medicines':'#dc2626', 'Courses & Certifications':'#4f46e5', 'Software & Subscriptions':'#9333ea', 'Banking & Finance':'#0284c7', 'Gifts & Donations':'#ec4899', Pets:'#a16207', Clothing:'#be185d', 'Personal Care':'#c026d3', Fitness:'#65a30d', 'Movies & Streaming':'#7c3aed', 'Dining Out':'#ea580c', 'Rent & Housing':'#059669', Utilities:'#eab308' }; return safeColor(category?.color || colors[category?.name], colors[category?.name] || colors.Other); }
function donutChart(summary = {}) {
  const entries = Object.entries(summary).filter(([,v]) => Number(v) > 0);
  const total = entries.reduce((s,[,v]) => s + Number(v), 0);
  if (!entries.length || total <= 0) return tableEmpty('No expense data yet.');
  let cursor = 0;
  const stops = entries.map(([name, amount]) => { const start = cursor; cursor += Number(amount) / total * 360; return `${categoryColor({name})} ${start}deg ${cursor}deg`; }).join(',');
  return `<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops})"><div class="donut-hole"><strong>₹${total.toFixed(0)}</strong><span>Total</span></div></div><div class="chart-legend">${entries.map(([name,amount])=>`<div><span><i class="category-dot" style="background:${categoryColor({name})}"></i>${escapeHtml(name)}</span><b>${(Number(amount)/total*100).toFixed(1)}%</b></div>`).join('')}</div></div>`;
}
function cashflowChart(income, expense) {
  const vals = [Number(income)||0, Number(expense)||0], max = Math.max(...vals, 1), labels=['Income','Expense'];
  return `<div class="cashflow-chart">${vals.map((v,i)=>`<div class="cash-bar"><div class="cash-value">₹${v.toFixed(0)}</div><div class="cash-track"><i class="cash-fill ${i?'expense':'income'}" style="height:${Math.max(6,v/max*100)}%"></i></div><b>${labels[i]}</b></div>`).join('')}</div>`;
}
function trendChart(expenses = [], incomes = []) {
  const now = new Date(); const months=[];
  for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push({key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label:d.toLocaleString('en-IN',{month:'short'})});}
  const sums=months.map(m=>({income:0,expense:0,...m}));
  incomes.forEach(x=>{const key=String(x.date||'').slice(0,7), row=sums.find(r=>r.key===key);if(row)row.income+=Number(x.amount)||0;});
  expenses.forEach(x=>{const key=String(x.date||'').slice(0,7), row=sums.find(r=>r.key===key);if(row)row.expense+=Number(x.amount)||0;});
  const max=Math.max(1,...sums.flatMap(r=>[r.income,r.expense])); const w=640,h=230,p=35,innerW=w-p*2,innerH=160;
  const points=(key)=>sums.map((r,i)=>`${p+i*(innerW/5)},${p+innerH-(r[key]/max*innerH)}`).join(' ');
  const dots=(key,cls)=>sums.map((r,i)=>{const x=p+i*(innerW/5),y=p+innerH-(r[key]/max*innerH);return `<circle class="${cls}" cx="${x}" cy="${y}" r="4"/>`;}).join('');
  return `<div class="trend-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Six month income and expense trend"><line x1="35" y1="195" x2="605" y2="195" class="chart-axis"/><polyline points="${points('income')}" class="trend-income"/><polyline points="${points('expense')}" class="trend-expense"/>${dots('income','trend-income-dot')}${dots('expense','trend-expense-dot')}${sums.map((r,i)=>`<text x="${p+i*(innerW/5)}" y="218" text-anchor="middle">${r.label}</text>`).join('')}</svg><div class="chart-key"><span><i class="key-income"></i>Income</span><span><i class="key-expense"></i>Expense</span></div></div>`;
}
function navLinks() {
  const user = currentUser();
  const admin = user.role === 'ADMIN' ? '<a href="admin.html">Admin</a><a href="admin-users.html">Users</a><a href="admin-audit-logs.html">Audit Logs</a>' : '';
  return `<a href="dashboard.html">Dashboard</a><a href="expenses.html">Expenses</a><a href="income.html">Income</a><a href="budgets.html">Budgets</a><a href="categories.html">Categories</a><a href="notifications.html">Notifications</a><a href="reports.html">Reports</a><a href="profile.html">Profile</a>${admin}<button class="theme-toggle" id="themeToggle" type="button">🌙 Dark</button><a href="#" id="logout">Logout</a>`;
}
function renderNavigation() {
  const header = $('header');
  if (!header || ['login', 'register', 'index'].includes(pageName)) return;
  const nav = header.querySelector('nav');
  if (nav) { nav.innerHTML = navLinks(); bindThemeToggle(); }
  $('#logout')?.addEventListener('click', (event) => { event.preventDefault(); localStorage.removeItem('smartspend_token'); localStorage.removeItem('smartspend_user'); location.href = 'login.html'; });
}
function authForm(mode) {
  const register = mode === 'register';
  return `<div class="auth-card"><div class="auth-brand">SmartSpend</div><h1>${register ? 'Create your account' : 'Welcome back'}</h1><p class="muted">${register ? 'Start building better money habits.' : 'Sign in to manage your finances.'}</p><form id="authForm"><label>${register ? 'Full name' : 'Email'}${register ? '<input name="name" required autocomplete="name">' : '<input name="email" type="email" required autocomplete="email">'}</label>${register ? '<label>Email<input name="email" type="email" required autocomplete="email"></label>' : ''}<label>Password<div class="password-wrap"><input name="password" type="password" minlength="6" required autocomplete="current-password"><button type="button" class="icon-button" id="togglePassword">Show</button></div></label>${register ? '<label>Confirm password<input name="confirmPassword" type="password" minlength="6" required></label>' : ''}<button class="primary wide" type="submit">${register ? 'Create account' : 'Log in'}</button><p id="message" class="message"></p></form><p class="auth-link">${register ? 'Already have an account?' : 'Don’t have an account?'} <a href="${register ? 'login.html' : 'register.html'}">${register ? 'Log in' : 'Register'}</a></p></div>`;
}
async function renderAuth(mode) {
  const app = $('#app');
  app.innerHTML = authForm(mode);
  $('#togglePassword').addEventListener('click', () => { const input = document.querySelector('input[name="password"]'); input.type = input.type === 'password' ? 'text' : 'password'; $('#togglePassword').textContent = input.type === 'password' ? 'Show' : 'Hide'; });
  $('#authForm').addEventListener('submit', async (event) => {
    event.preventDefault(); showMessage('Working...', 'info');
    const data = Object.fromEntries(new FormData(event.target));
    if (mode === 'register') {
      if (data.password !== data.confirmPassword) return showMessage('Passwords do not match.', 'error');
      delete data.confirmPassword;
    }
    if (mode === 'login') {
      if (!data.email) return showMessage('Please enter your email.', 'error');
      if (!data.password) return showMessage('Please enter your password.', 'error');
    }
    try {
      const response = await fetch(`${API}/auth/${mode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
      let result = {};
      try { result = await response.json(); } catch (_) {}
      if (!response.ok) {
        if (mode === 'login' && response.status === 401) throw new Error('Invalid email or password.');
        throw new Error(result.message || 'Unable to complete the request.');
      }
      if (mode === 'register') { showMessage('Registration successful. Redirecting to login...', 'success'); setTimeout(() => { location.href = 'login.html'; }, 700); }
      else { localStorage.setItem('smartspend_token', result.token); localStorage.setItem('smartspend_user', JSON.stringify(result)); location.href = 'dashboard.html'; }
    } catch (error) { showMessage(error instanceof TypeError ? 'Unable to connect to the server. Please try again.' : error.message, 'error'); }
  });
}
function formField(label, name, type = 'text', extra = '') { return `<label>${label}<input name="${name}" type="${type}" ${extra}></label>`; }
function tableEmpty(message) { return `<div class="empty">${message}</div>`; }
function notificationTone(type) { if (/BUDGET_EXCEEDED|EXCEEDED/.test(type)) return 'tone-danger'; if (/BUDGET_WARNING|WARNING/.test(type)) return 'tone-warning'; if (/EXPENSE_CREATED/.test(type)) return 'tone-success'; return 'tone-info'; }
function savingsGoalCard(goal) {
  if (!goal || !goal.exists) return `<section class="panel savings-goal-panel"><div class="panel-heading"><div><h2>🎯 Savings goal</h2><p class="muted">Set a target and track your progress.</p></div></div><button class="primary" id="setGoal">Create savings goal</button></section>`;
  const target=Number(goal.targetAmount)||0,current=Number(goal.currentAmount)||0,pct=target?Math.min(100,current/target*100):0;
  return `<section class="panel savings-goal-panel"><div class="panel-heading"><div><h2>🎯 ${escapeHtml(goal.title)}</h2><p class="muted">${goal.deadline?`Target date: ${escapeHtml(goal.deadline)}`:'No target date set'}</p></div><button class="secondary" id="editGoal">Edit</button></div><div class="goal-amounts"><strong>₹${current.toFixed(2)}</strong><span>of ₹${target.toFixed(2)}</span></div><div class="goal-track"><i style="width:${pct}%"></i></div><div class="goal-footer"><b>${pct.toFixed(1)}%</b><span>${pct>=100?'Goal reached 🎉':'₹'+Math.max(0,target-current).toFixed(2)+' remaining'}</span><button class="ghost small" id="deleteGoal">Remove</button></div></section>`;
}
async function openSavingsGoalEditor(goal={}) {
  const current=Number(goal.currentAmount)||0;
  const target=Number(goal.targetAmount)||'';
  const title=goal.title||'';
  const deadline=goal.deadline||'';
  const panel=document.querySelector('.savings-goal-panel'); if(!panel)return;
  panel.innerHTML=`<h2>${goal.exists?'Edit':'Create'} savings goal</h2><form id="goalForm" class="goal-form">${formField('Goal name','title','text',`value="${escapeHtml(title)}" required`)}${formField('Target amount','targetAmount','number',`step="0.01" min="0.01" value="${target}" required`)}${formField('Current saved','currentAmount','number',`step="0.01" min="0" value="${current}" required`)}${formField('Deadline (optional)','deadline','date',`value="${deadline}"`)}<div><button class="primary">Save goal</button> <button type="button" class="ghost" id="cancelGoal">Cancel</button></div><p id="message" class="message"></p></form>`;
  $('#cancelGoal').onclick=renderDashboard;
  $('#goalForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));if(!body.deadline)delete body.deadline;try{await api('/savings-goal',{method:'POST',body:JSON.stringify(body)});await renderDashboard();}catch(err){showMessage(err.message,'error');}};
}
async function renderDashboard() {
  showLoading();
  const [data, insights, notifications, expenses, incomes, goal] = await Promise.all([api('/dashboard'), api('/insights'), api('/notifications'), api('/expenses?size=200&sortBy=date&sortDir=desc'), api('/incomes?size=200&sortBy=date&sortDir=desc'), api('/savings-goal')]);
  const summary = [['Total Income', data.totalIncome], ['Total Expense', data.totalExpense], ['Balance', data.balance], ['Savings', data.savings], ['Savings %', `${data.savingsPercentage}%`]];
  const bars = Object.entries(data.categorySummary || {}).map(([name, amount]) => `<div class="bar-row"><span><i class="category-dot" style="background:${categoryColor({name})}"></i>${categoryIcon(name)} ${escapeHtml(name)}</span><div class="bar"><i style="width:${Math.min(100, Number(amount) / (Number(data.totalExpense) || 1) * 100)}%;background:${categoryColor({name})}"></i></div><b>₹${amount}</b></div>`).join('') || tableEmpty('No expense data yet.');
  $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Overview</p><h1>Good to see you, ${escapeHtml(currentUser().name || 'there')}</h1><p class="muted">A clear view of your money, spending and budget health.</p></div></div><div class="metrics dashboard-metrics">${summary.map(([label, value]) => `<div class="metric-card"><span>${label}</span><strong>${label === 'Savings %' ? value : '₹' + value}</strong></div>`).join('')}</div><div class="chart-grid"><section class="panel chart-panel"><div class="panel-heading"><div><h2>Expense breakdown</h2><p class="muted">Where your money is going.</p></div></div>${donutChart(data.categorySummary || {})}</section><section class="panel chart-panel"><div class="panel-heading"><div><h2>Current month cash flow</h2><p class="muted">Income compared with expenses.</p></div></div>${cashflowChart(data.currentMonthIncome, data.currentMonthExpense)}</section></div><section class="panel chart-panel trend-panel"><div class="panel-heading"><div><h2>Six-month trend</h2><p class="muted">Income and expense movement over time.</p></div></div>${trendChart(expenses, incomes)}</section>${savingsGoalCard(goal)}<div class="split"><section class="panel dashboard-category"><h2>Category spending</h2>${bars}</section><section class="panel dashboard-month"><h2>Current month</h2><div class="mini-stat"><span>Income</span><b>₹${data.currentMonthIncome}</b></div><div class="mini-stat"><span>Expenses</span><b>₹${data.currentMonthExpense}</b></div><div class="mini-stat"><span>Previous month expenses</span><b>₹${data.previousMonthExpense}</b></div><div class="mini-stat"><span>Trend</span><b class="${data.spendingIncreased?'text-danger':'text-success'}">${data.spendingIncreased?'↑ Increased':'↓/— Stable'}</b></div></section></div><div class="split"><section class="panel dashboard-insights"><h2>Spending insights</h2>${insights.length ? insights.map(i => `<div class="alert ${i.severity}"><b>${escapeHtml(i.title)}</b><br>${escapeHtml(i.message)}</div>`).join('') : tableEmpty('No insights yet.')}</section><section class="panel dashboard-notifications"><h2>Recent notifications</h2>${notifications.slice(0, 4).map(n => `<div class="notification-line"><b>${escapeHtml(n.type)}</b><span>${escapeHtml(n.message)}</span></div>`).join('') || tableEmpty('No notifications yet.')}</section></div>`;
  $('#setGoal')?.addEventListener('click',()=>openSavingsGoalEditor(goal)); $('#editGoal')?.addEventListener('click',()=>openSavingsGoalEditor(goal)); $('#deleteGoal')?.addEventListener('click',async()=>{if(confirm('Remove this savings goal?')){await api('/savings-goal',{method:'DELETE'});await renderDashboard();}});
}

async function loadCategories() { return api('/categories'); }
function categoryOptions(categories, selected = '') { return '<option value="">Select category</option>' + categories.map(c => `<option value="${c.id}" ${String(c.id) === String(selected) ? 'selected' : ''}>${escapeHtml(c.name)}</option>`).join(''); }
function paymentOptions(selected = '') { return '<option value="">Select payment method</option>' + [['CASH', 'Cash'], ['CARD', 'Card'], ['UPI', 'UPI'], ['NET_BANKING', 'Net banking'], ['WALLET', 'Wallet']].map(([v, l]) => `<option value="${v}" ${v === selected ? 'selected' : ''}>${l}</option>`).join(''); }
async function renderExpenses() {
  showLoading(); const categories = await loadCategories(); let page=0,size=20; let state={search:'',from:'',to:'',category:'',payment:'',month:new Date().getMonth(),year:new Date().getFullYear()};
  $('#app').innerHTML=`<div class="page-heading"><div><p class="eyebrow">Transactions</p><h1>Expenses</h1><p class="muted">Track, filter and review every expense.</p></div><button class="primary" id="newExpense">Add expense</button></div><section class="panel" id="expenseForm" hidden></section><section class="panel filters"><input id="searchExpense" placeholder="Search description"><input id="fromDate" type="date"><input id="toDate" type="date"><select id="filterCategory">${categoryOptions(categories)}</select><select id="filterPayment">${paymentOptions()}</select><button class="secondary" id="applyFilters">Apply filters</button><button class="ghost" id="clearFilters">Clear</button></section><section class="panel"><div id="expenseTable"></div></section><section class="panel calendar-panel"><div class="calendar-head"><div><h2>📅 Expense calendar</h2><p class="muted">Daily spending for the selected month.</p></div><div class="calendar-nav"><button class="small" id="prevMonth">←</button><strong id="calendarMonth"></strong><button class="small" id="nextMonth">→</button></div></div><div id="calendarGrid"></div><div id="calendarDetails" class="calendar-details"></div></section>`;
  const formHtml=(item={})=>`<h2>${item.id?'Edit expense':'Add expense'}</h2><form id="expenseEditor" class="inline-form">${formField('Amount','amount','number',`step="0.01" min="0.01" value="${item.amount||''}" required`)}${formField('Description','description','text',`value="${escapeHtml(item.description||'')}" required`)}${formField('Date','date','date',`value="${item.date||new Date().toISOString().slice(0,10)}" required`)}<label>Category<select name="categoryId" required>${categoryOptions(categories,item.category?.id)}</select></label><label>Payment method<select name="paymentMethod" required>${paymentOptions(item.paymentMethod)}</select></label><button class="primary">Save expense</button><button type="button" class="ghost" id="cancelExpense">Cancel</button><p id="message" class="message"></p></form>`;
  const bindEditor=id=>{$('#cancelExpense').onclick=()=>{$('#expenseForm').hidden=true;};$('#expenseEditor').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{await api(id?`/expenses/${id}`:'/expenses',{method:id?'PUT':'POST',body:JSON.stringify(body)});location.reload();}catch(err){showMessage(err.message,'error');}}};
  const draw=async()=>{const qs=new URLSearchParams({page:String(page),size:String(size),sortBy:'date',sortDir:'desc'});if(state.search)qs.set('search',state.search);if(state.from)qs.set('from',state.from);if(state.to)qs.set('to',state.to);if(state.category)qs.set('categoryId',state.category);if(state.payment)qs.set('paymentMethod',state.payment);const list=await api('/expenses?'+qs);$('#expenseTable').innerHTML=list.length?`<table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Payment</th><th>Amount</th><th>Actions</th></tr></thead><tbody>${list.map(e=>`<tr><td>${e.date}</td><td>${escapeHtml(e.description)}</td><td><span class="category-chip" style="--chip:${categoryColor(e.category)}">${categoryIcon(e.category.name)} ${escapeHtml(e.category.name)}</span></td><td>${e.paymentMethod}</td><td>₹${e.amount}</td><td><button class="small" data-edit="${e.id}">Edit</button> <button class="small danger" data-delete="${e.id}">Delete</button></td></tr>`).join('')}</tbody></table><div class="pagination"><button class="small" id="prevPage" ${page===0?'disabled':''}>Previous</button><span>Page ${page+1}</span><button class="small" id="nextPage" ${list.length<size?'disabled':''}>Next</button></div>`:tableEmpty('No expenses found for the selected filters.');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const item=list.find(e=>String(e.id)===b.dataset.edit);$('#expenseForm').hidden=false;$('#expenseForm').innerHTML=formHtml(item);bindEditor(item.id);});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this expense?')){await api(`/expenses/${b.dataset.delete}`,{method:'DELETE'});draw();loadCalendar();}});$('#prevPage')?.addEventListener('click',()=>{if(page>0){page--;draw();}});$('#nextPage')?.addEventListener('click',()=>{if(list.length===size){page++;draw();}});};
  const loadCalendar=async()=>{const start=new Date(state.year,state.month,1),end=new Date(state.year,state.month+1,0),from=`${state.year}-${String(state.month+1).padStart(2,'0')}-01`,to=`${state.year}-${String(state.month+1).padStart(2,'0')}-${String(end.getDate()).padStart(2,'0')}`;const list=await api(`/expenses?from=${from}&to=${to}&size=200&sortBy=date&sortDir=asc`);const byDay={};list.forEach(e=>{(byDay[e.date]??=[]).push(e);});$('#calendarMonth').textContent=start.toLocaleString('en-IN',{month:'long',year:'numeric'});const first=start.getDay(),days=end.getDate();let cells=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="cal-weekday">${d}</div>`).join('');for(let i=0;i<first;i++)cells+='<div class="cal-day muted-day"></div>';for(let d=1;d<=days;d++){const key=`${state.year}-${String(state.month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,items=byDay[key]||[],total=items.reduce((sum,e)=>sum+Number(e.amount),0);cells+=`<button class="cal-day ${items.length?'has-expense':''}" data-day="${key}"><strong>${d}</strong>${items.length?`<span>₹${total.toFixed(0)}</span>`:''}</button>`;}$('#calendarGrid').innerHTML=`<div class="calendar-grid">${cells}</div>`;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{const items=byDay[b.dataset.day]||[];$('#calendarDetails').innerHTML=items.length?`<b>${b.dataset.day}</b>${items.map(e=>`<div><span>${categoryIcon(e.category.name)} ${escapeHtml(e.description)}</span><strong>₹${e.amount}</strong></div>`).join('')}`:`<span class="muted">No expenses on ${b.dataset.day}.</span>`;});};
  $('#newExpense').onclick=()=>{$('#expenseForm').hidden=false;$('#expenseForm').innerHTML=formHtml();bindEditor();};$('#applyFilters').onclick=()=>{state.search=$('#searchExpense').value.trim();state.from=$('#fromDate').value;state.to=$('#toDate').value;state.category=$('#filterCategory').value;state.payment=$('#filterPayment').value;page=0;draw();};$('#clearFilters').onclick=()=>{document.querySelectorAll('.filters input').forEach(i=>i.value='');$('#filterCategory').value='';$('#filterPayment').value='';state={...state,search:'',from:'',to:'',category:'',payment:''};page=0;draw();};$('#prevMonth').onclick=()=>{state.month--;if(state.month<0){state.month=11;state.year--;}loadCalendar();};$('#nextMonth').onclick=()=>{state.month++;if(state.month>11){state.month=0;state.year++;}loadCalendar();};await draw();await loadCalendar();
}

async function renderIncome() {
  showLoading(); let page=0,size=20,state={search:'',from:'',to:''};
  const draw=async()=>{const qs=new URLSearchParams({page:String(page),size:String(size),sortBy:'date',sortDir:'desc'});if(state.search)qs.set('search',state.search);if(state.from)qs.set('from',state.from);if(state.to)qs.set('to',state.to);const list=await api('/incomes?'+qs);$('#incomeTable').innerHTML=list.length?`<table><tr><th>Date</th><th>Source</th><th>Description</th><th>Amount</th><th>Actions</th></tr>${list.map(i=>`<tr><td>${i.date}</td><td>${escapeHtml(i.source)}</td><td>${escapeHtml(i.description)}</td><td>₹${i.amount}</td><td><button class="small" data-edit-income="${i.id}">Edit</button> <button class="small danger" data-delete-income="${i.id}">Delete</button></td></tr>`).join('')}</table><div class="pagination"><button class="small" id="prevIncome" ${page===0?'disabled':''}>Previous</button><span>Page ${page+1}</span><button class="small" id="nextIncome" ${list.length<size?'disabled':''}>Next</button></div>`:tableEmpty('No income records found.');document.querySelectorAll('[data-edit-income]').forEach(b=>b.onclick=()=>openEditor(list.find(i=>String(i.id)===b.dataset.editIncome)));document.querySelectorAll('[data-delete-income]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this income?')){await api(`/incomes/${b.dataset.deleteIncome}`,{method:'DELETE'});draw();}});$('#prevIncome')?.addEventListener('click',()=>{if(page>0){page--;draw();}});$('#nextIncome')?.addEventListener('click',()=>{if(list.length===size){page++;draw();}});};
  const openEditor=(item={})=>{$('#incomeForm').hidden=false;$('#incomeForm').innerHTML=`<h2>${item.id?'Edit income':'Add income'}</h2><form id="incomeEditor">${formField('Amount','amount','number',`step="0.01" min="0.01" value="${item.amount||''}" required`)}${formField('Source','source','text',`value="${escapeHtml(item.source||'')}" required`)}${formField('Description','description','text',`value="${escapeHtml(item.description||'')}"`)}${formField('Date','date','date',`value="${item.date||new Date().toISOString().slice(0,10)}" required`)}<button class="primary">Save income</button><button type="button" class="ghost" id="cancelIncome">Cancel</button><p id="message" class="message"></p></form>`;$('#cancelIncome').onclick=()=>{$('#incomeForm').hidden=true;};$('#incomeEditor').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{await api(item.id?`/incomes/${item.id}`:'/incomes',{method:item.id?'PUT':'POST',body:JSON.stringify(body)});location.reload();}catch(err){showMessage(err.message,'error');}}};
  $('#app').innerHTML=`<div class="page-heading"><div><p class="eyebrow">Cash flow</p><h1>Income</h1><p class="muted">Track every source of incoming money.</p></div><button class="primary" id="newIncome">Add income</button></div><section class="panel" id="incomeForm" hidden></section><section class="panel filters income-filters"><input id="incomeSearch" placeholder="Search source or description"><input id="incomeFrom" type="date"><input id="incomeTo" type="date"><button class="secondary" id="applyIncome">Apply filters</button><button class="ghost" id="clearIncome">Clear</button></section><section class="panel"><div id="incomeTable"></div></section>`;$('#newIncome').onclick=()=>openEditor();$('#applyIncome').onclick=()=>{state.search=$('#incomeSearch').value.trim();state.from=$('#incomeFrom').value;state.to=$('#incomeTo').value;page=0;draw();};$('#clearIncome').onclick=()=>{$('#incomeSearch').value='';$('#incomeFrom').value='';$('#incomeTo').value='';state={search:'',from:'',to:''};page=0;draw();};await draw();
}

async function renderBudgets() { showLoading(); const [budgets, categories] = await Promise.all([api('/budgets'), loadCategories()]); $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Planning</p><h1>Budgets</h1></div><button class="primary" id="newBudget">Create budget</button></div><section class="panel" id="budgetForm" hidden></section><section class="panel"><div id="budgetTable">${budgets.length ? `<table><tr><th>Period</th><th>Category</th><th>Budget</th><th>Spent</th><th>Remaining</th><th>Usage</th><th>Status</th><th>Actions</th></tr>${budgets.map(b => `<tr><td>${b.month}/${b.year}</td><td>${escapeHtml(b.category)}</td><td>₹${b.amount}</td><td>₹${b.used}</td><td>₹${b.remaining}</td><td>${Number(b.percentage).toFixed(1)}%</td><td><span class="badge ${b.status}">${b.status}</span></td><td><button class="small" data-edit-budget="${b.id}">Edit</button> <button class="small danger" data-delete-budget="${b.id}">Delete</button></td></tr>`).join('')}</table>` : tableEmpty('No budgets created yet.')}</div></section>`; const open = (item = {}) => { if (item && item.category !== 'Overall') item.categoryId = categories.find(c => c.name === item.category)?.id || ''; $('#budgetForm').hidden = false; $('#budgetForm').innerHTML = `<h2>${item.id ? 'Edit budget' : 'Create budget'}</h2><form id="budgetEditor">${formField('Budget amount', 'amount', 'number', `step="0.01" min="0.01" value="${item.amount || ''}" required`)}${formField('Month', 'month', 'number', `min="1" max="12" value="${item.month || new Date().getMonth() + 1}" required`)}${formField('Year', 'year', 'number', `min="2000" value="${item.year || new Date().getFullYear()}" required`)}<label>Category (optional)<select name="categoryId"><option value="">Overall budget</option>${categoryOptions(categories, item.categoryId || '')}</select></label><button class="primary">Save budget</button><button type="button" class="ghost" id="cancelBudget">Cancel</button></form>`; $('#cancelBudget').onclick = () => { $('#budgetForm').hidden = true; }; $('#budgetEditor').onsubmit = async (e) => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.target)); if (!body.categoryId) delete body.categoryId; await api(item.id ? `/budgets/${item.id}` : '/budgets', { method: item.id ? 'PUT' : 'POST', body: JSON.stringify(body) }); location.reload(); }; }; $('#newBudget').onclick = () => open(); document.querySelectorAll('[data-edit-budget]').forEach(b => b.onclick = () => open(budgets.find(x => String(x.id) === b.dataset.editBudget))); document.querySelectorAll('[data-delete-budget]').forEach(b => b.onclick = async () => { if (confirm('Delete this budget?')) { await api(`/budgets/${b.dataset.deleteBudget}`, { method: 'DELETE' }); location.reload(); } }); }
async function renderCategories() { showLoading(); const categories = await loadCategories(); const admin = currentUser().role === 'ADMIN'; $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Organization</p><h1>Categories</h1></div></div>${admin ? '<section class="panel"><form id="categoryForm" class="inline-form">'+formField('Category name', 'name', 'text', 'required')+formField('Color', 'color', 'color', 'value="#38bdf8"')+'<button class="primary">Add category</button><p id="message" class="message"></p></form></section>' : ''}<section class="category-grid">${categories.map(c => `<div class="category-card" style="--category-accent:${categoryColor(c)}"><span class="category-icon">${categoryIcon(c.name)}</span><i style="background:${categoryColor(c)}"></i><b>${escapeHtml(c.name)}</b>${admin ? `<button class="small" data-edit-category="${c.id}">Edit</button><button class="small danger" data-delete-category="${c.id}">Delete</button>` : ''}</div>`).join('') || tableEmpty('No categories found.')}</section>`; $('#categoryForm')?.addEventListener('submit', async (e) => { e.preventDefault(); await api('/categories', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(e.target))) }); location.reload(); }); document.querySelectorAll('[data-edit-category]').forEach(b => b.onclick = async () => { const c=categories.find(x=>String(x.id)===b.dataset.editCategory); const name=prompt('Category name',c.name); if(name&&name.trim()){ await api('/categories/'+c.id,{method:'PUT',body:JSON.stringify({name:name.trim(),color:c.color||'#38bdf8'})}); location.reload(); } }); document.querySelectorAll('[data-delete-category]').forEach(b => b.onclick = async () => { if (confirm('Delete this category? It must not be used by existing records.')) { await api(`/categories/${b.dataset.deleteCategory}`, { method: 'DELETE' }); location.reload(); } }); }
async function renderNotifications() {
  showLoading();
  const items = await api('/notifications');
  const unread = items.filter(n => !n.read).length;
  $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Updates</p><h1>Notifications</h1><p class="muted">${unread ? `${unread} unread notification${unread === 1 ? '' : 's'}` : 'You are all caught up.'}</p></div><button class="secondary" id="readAll" ${unread ? '' : 'disabled'}>Mark all as read</button></div><section class="panel notification-panel">${items.length ? items.map(n => `<div class="notification-card ${notificationTone(n.type)} ${n.read ? '' : 'unread'}"><div><b>${escapeHtml(n.type.replaceAll('_',' '))}</b><p>${escapeHtml(n.message)}</p><small>${escapeHtml(n.createdAt || '')}</small></div>${n.read ? '<span class="badge SAFE">Read</span>' : `<button class="small" data-read="${n.id}">Mark read</button>`}</div>`).join('') : tableEmpty('No notifications found.')}</section>`;
  const readAll=$('#readAll');
  if(readAll) readAll.onclick=async()=>{readAll.disabled=true;readAll.textContent='Updating...';try{await api('/notifications/read-all',{method:'PUT'});await renderNotifications();}catch(e){readAll.disabled=false;readAll.textContent='Mark all as read';showMessage(e.message,'error');}};
  document.querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Saving...';try{await api(`/notifications/${b.dataset.read}/read`,{method:'PUT'});await renderNotifications();}catch(e){b.disabled=false;b.textContent='Mark read';showMessage(e.message,'error');}});
}
async function renderReports() { $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Documents</p><h1>Reports</h1></div></div><section class="panel report-panel"><h2>Monthly financial report</h2><p class="muted">Generate a PDF containing totals, transactions, budgets, categories, and insights.</p><form id="reportForm">${formField('Month', 'month', 'number', `min="1" max="12" value="${new Date().getMonth() + 1}" required`)}${formField('Year', 'year', 'number', `min="2000" value="${new Date().getFullYear()}" required`)}<button class="primary">Generate Monthly PDF Report</button><p id="message" class="message"></p></form></section>`; $('#reportForm').onsubmit = async (e) => { e.preventDefault(); showMessage('Generating PDF...', 'info'); const data = Object.fromEntries(new FormData(e.target)); try { const response = await fetch(`${API}/reports/monthly?month=${data.month}&year=${data.year}`, { headers: { Authorization: `Bearer ${token()}` } }); if (!response.ok) throw new Error('Unable to generate the report.'); const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `SmartSpend-Monthly-Report-${data.year}-${String(data.month).padStart(2, '0')}.pdf`; link.click(); showMessage('Report downloaded successfully.', 'success'); } catch (error) { showMessage(error.message, 'error'); } }; }
async function renderProfile() {
  const user = currentUser(); showLoading('Loading profile...');
  const [data, budgets] = await Promise.all([api('/dashboard'), api('/budgets')]);
  const budgetRows = budgets.slice(0, 5).map(b => `<div class="profile-budget-row"><span><i class="category-dot" style="background:${categoryColor({name:b.category})}"></i>${categoryIcon(b.category)} ${escapeHtml(b.category)}</span><span>${Number(b.percentage).toFixed(1)}%</span><span class="badge ${escapeHtml(b.status)}">${escapeHtml(b.status)}</span></div>`).join('') || tableEmpty('No budgets created yet.');
  const savings = Number(data.savings) || 0;
  const savingsPct = Number(data.savingsPercentage) || 0;
  $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Account</p><h1>Your profile</h1><p class="muted">Your account details and financial snapshot in one place.</p></div><button class="secondary" id="profileLogout">Logout</button></div><div class="profile-layout"><section class="profile-card"><div class="profile-avatar-wrap"><div class="avatar">${escapeHtml((user.name || 'U').charAt(0).toUpperCase())}</div><span class="profile-avatar-label">${escapeHtml(user.role || 'USER')}</span></div><h2>${escapeHtml(user.name || 'User')}</h2><p>${escapeHtml(user.email || '')}</p><dl><dt>Role</dt><dd>${escapeHtml(user.role || 'USER')}</dd><dt>Account status</dt><dd><span class="badge SAFE">Active</span></dd><dt>Member since</dt><dd>${escapeHtml(user.createdAt || 'Local account')}</dd></dl><p class="muted">Password, JWT, and secret values are never displayed.</p></section><div class="profile-side"><section class="panel profile-snapshot"><div class="panel-heading"><div><h2>📊 Financial Snapshot</h2><p class="muted">Your current overall financial position.</p></div></div><div class="profile-stats"><div><span>Total income</span><b>₹${data.totalIncome}</b></div><div><span>Total expenses</span><b>₹${data.totalExpense}</b></div><div><span>Balance</span><b>₹${data.balance}</b></div><div><span>Savings rate</span><b>${savingsPct.toFixed(2)}%</b></div></div><div class="profile-savings"><div><span>Savings</span><strong>₹${savings.toFixed(2)}</strong></div><div class="savings-mini-track"><i style="width:${Math.max(0,Math.min(100,savingsPct))}%"></i></div><small>${savingsPct >= 0 ? 'Keep building your financial cushion.' : 'Expenses currently exceed income.'}</small></div></section><section class="panel profile-budget-health"><div class="panel-heading"><div><h2>🎯 Budget Health</h2><p class="muted">A quick view of your active budget status.</p></div><a href="budgets.html">View budgets →</a></div>${budgetRows}</section></div></div>`;
  $('#profileLogout').onclick = () => { localStorage.removeItem('smartspend_token'); localStorage.removeItem('smartspend_user'); location.href = 'login.html'; };
}
async function renderAdmin(mode = 'admin') {
  showLoading();
  if (mode === 'admin') {
    const stats = await api('/admin/stats');
    $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Administration</p><h1>System overview</h1><p class="muted">Monitor the SmartSpend platform and manage users.</p></div></div><div class="metrics admin-metrics"><div class="metric-card"><span>Total users</span><strong>${stats.users}</strong></div><div class="metric-card"><span>Active users</span><strong>${stats.activeUsers}</strong></div><div class="metric-card"><span>Inactive users</span><strong>${stats.inactiveUsers}</strong></div><div class="metric-card"><span>Admins</span><strong>${stats.admins}</strong></div><div class="metric-card"><span>Categories</span><strong>${stats.categories}</strong></div></div><div class="admin-links"><a href="admin-users.html">Manage users <span>→</span></a><a href="admin-audit-logs.html">Review audit logs <span>→</span></a><a href="notifications.html">Admin notifications <span>→</span></a></div>`;
  } else if (mode === 'admin-users') {
    const users = await api('/admin/users');
    $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Administration</p><h1>User management</h1><p class="muted">Select a user to view their dashboard in read-only mode.</p></div></div><section class="panel"><div class="admin-user-toolbar"><input id="userSearch" placeholder="Search by name or email"><span class="muted" id="userCount">${users.length} users</span></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody id="userRows"></tbody></table></div></section>`;
    const draw=()=>{const term=($('#userSearch').value||'').trim().toLowerCase();const filtered=users.filter(u=>`${u.name} ${u.email}`.toLowerCase().includes(term));$('#userCount').textContent=`${filtered.length} of ${users.length} users`;$('#userRows').innerHTML=filtered.map(u=>`<tr><td><div class="user-cell"><span class="table-avatar">${escapeHtml((u.name||'U').charAt(0).toUpperCase())}</span><b>${escapeHtml(u.name)}</b></div></td><td>${escapeHtml(u.email)}</td><td><span class="role-pill">${u.role}</span></td><td><span class="badge ${u.active?'SAFE':'DANGER'}">${u.active?'Active':'Inactive'}</span></td><td>${escapeHtml(u.createdAt||'')}</td><td><div class="action-row"><button class="small primary-soft" data-view-user="${u.id}">View dashboard</button><button class="small" data-status="${u.id}" data-value="${!u.active}">${u.active?'Deactivate':'Activate'}</button></div></td></tr>`).join('')||`<tr><td colspan="6">${tableEmpty('No matching users found.')}</td></tr>`;document.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{if(confirm('Change this user status?')){await api(`/admin/users/${b.dataset.status}/active?value=${b.dataset.value}`,{method:'PUT'});location.reload();}});document.querySelectorAll('[data-view-user]').forEach(b=>b.onclick=()=>location.href=`admin-user-dashboard.html?userId=${b.dataset.viewUser}`);};
    draw(); $('#userSearch').oninput=draw;
  } else {
    const logs = await api('/admin/audit-logs');
    $('#app').innerHTML = `<div class="page-heading"><div><p class="eyebrow">Administration</p><h1>Audit logs</h1></div></div><section class="panel"><div class="table-wrap"><table><tr><th>Timestamp</th><th>Action</th><th>Description</th><th>User</th></tr>${logs.map(l => `<tr><td>${escapeHtml(l.timestamp)}</td><td>${escapeHtml(l.action)}</td><td>${escapeHtml(l.description)}</td><td>${escapeHtml(l.user)}</td></tr>`).join('') || '<tr><td colspan="4">No audit records found.</td></tr>'}</table></div></section>`;
  }
}
async function renderAdminUserDashboard() {
  showLoading();
  if(currentUser().role!=='ADMIN') throw new Error('You do not have permission to view user dashboards.');
  const id=new URLSearchParams(location.search).get('userId');
  if(!id) throw new Error('No user was selected.');
  const data=await api(`/admin/users/${encodeURIComponent(id)}/dashboard`);
  const u=data.user;
  const catTotal=Number(data.totalExpense)||0;
  const cats=Object.entries(data.categorySummary||{}).map(([name,amount])=>`<div class="bar-row"><span><i class="category-dot" style="background:${categoryColor({name})}"></i>${escapeHtml(name)}</span><div class="bar"><i style="width:${Math.min(100,Number(amount)/(catTotal||1)*100)}%;background:${categoryColor({name})}"></i></div><b>₹${amount}</b></div>`).join('')||tableEmpty('No expense data yet.');
  const budgets=(data.budgets||[]).map(b=>`<div class="admin-budget-row"><div><b>${escapeHtml(b.category)}</b><small>${b.month}/${b.year}</small></div><span>₹${b.used} / ₹${b.amount}</span><span class="badge ${escapeHtml(b.status)}">${escapeHtml(b.status)}</span></div>`).join('')||tableEmpty('No budgets found.');
  const insights=(data.insights||[]).map(i=>`<div class="alert ${escapeHtml(i.severity)}"><b>${escapeHtml(i.title)}</b><br>${escapeHtml(i.message)}</div>`).join('')||tableEmpty('No insights for this user.');
  const tx=(data.recentExpenses||[]).map(e=>`<tr><td>${escapeHtml(e.date)}</td><td>${escapeHtml(e.category)}</td><td>${escapeHtml(e.description)}</td><td>${escapeHtml(e.paymentMethod)}</td><td>₹${escapeHtml(e.amount)}</td></tr>`).join('')||'<tr><td colspan="5">No expenses found.</td></tr>';
  $('#app').innerHTML=`<div class="page-heading"><div><p class="eyebrow">Admin · Read-only view</p><h1>${escapeHtml(u.name)}'s dashboard</h1><p class="muted">${escapeHtml(u.email)} · <span class="badge ${u.active?'SAFE':'DANGER'}">${u.active?'Active':'Inactive'}</span></p></div><a class="secondary button-link" href="admin-users.html">← Back to users</a></div><section class="user-profile-banner"><div class="avatar large-avatar">${escapeHtml((u.name||'U').charAt(0).toUpperCase())}</div><div><h2>${escapeHtml(u.name)}</h2><p>${escapeHtml(u.email)}</p><span class="role-pill">${escapeHtml(u.role)}</span></div><div class="readonly-badge">READ ONLY</div></section><div class="metrics dashboard-metrics"><div class="metric-card"><span>Total income</span><strong>₹${data.totalIncome}</strong></div><div class="metric-card"><span>Total expense</span><strong>₹${data.totalExpense}</strong></div><div class="metric-card"><span>Balance</span><strong>₹${data.balance}</strong></div><div class="metric-card"><span>Savings</span><strong>₹${data.savings}</strong></div><div class="metric-card"><span>Savings %</span><strong>${data.savingsPercentage}%</strong></div></div><div class="split"><section class="panel dashboard-category"><h2>Category spending</h2>${cats}</section><section class="panel dashboard-month"><h2>Current month</h2><div class="mini-stat"><span>Income</span><b>₹${data.currentMonthIncome}</b></div><div class="mini-stat"><span>Expenses</span><b>₹${data.currentMonthExpense}</b></div><div class="mini-stat"><span>Previous month expenses</span><b>₹${data.previousMonthExpense}</b></div><div class="mini-stat"><span>Trend</span><b class="${data.spendingIncreased?'text-danger':'text-success'}">${data.spendingIncreased?'↑ Increased':'↓/— Stable'}</b></div></section></div><div class="split"><section class="panel"><h2>Budget overview</h2>${budgets}</section><section class="panel"><h2>Spending insights</h2>${insights}</section></div><section class="panel"><h2>Recent expenses</h2><div class="table-wrap"><table><tr><th>Date</th><th>Category</th><th>Description</th><th>Payment</th><th>Amount</th></tr>${tx}</table></div></section>`;
}
async function renderPage() { renderNavigation(); if (['login', 'register'].includes(pageName)) return renderAuth(pageName); if (!token() && pageName !== 'index') return (location.href = 'login.html'); const routes = { dashboard: renderDashboard, expenses: renderExpenses, income: renderIncome, budgets: renderBudgets, categories: renderCategories, notifications: renderNotifications, reports: renderReports, profile: renderProfile, admin: () => renderAdmin('admin'), 'admin-users': () => renderAdmin('admin-users'), 'admin-audit-logs': () => renderAdmin('admin-audit-logs'), 'admin-user-dashboard': renderAdminUserDashboard }; try { if (routes[pageName]) await routes[pageName](); else if ($('#app')) $('#app').innerHTML = tableEmpty('Choose a module from the navigation.'); } catch (error) { if ($('#app')) $('#app').innerHTML = `<div class="alert DANGER">${escapeHtml(error.message)} <button onclick="location.reload()">Try again</button></div>`; } }
document.addEventListener('DOMContentLoaded', () => { initTheme(); renderPage(); });
